-i in fthist

diff --git a/dirgraph b/dirgraph
--- a/dirgraph
+++ b/dirgraph
@@ -9,6 +9,22 @@ FSHIST_PREFIX_LEN=12
 FTHIST_PREFIX_LEN=47
 LINE_LEN=79
 
+# Test is utilities exist
+if ! wc < /dev/null > /dev/null; then
+	echo "Error: Utility 'wc' not found!" >&2
+	exit 2
+fi
+
+if ! sed '' /dev/null; then
+	echo "Error: Utility 'sed' not found!" >&2
+	exit 2
+fi
+
+if ! awk '' /dev/null; then
+	echo "Error: Utility 'awk' not found!" >&2
+	exit 2
+fi
+
 if [ -t 1 ]; then
 	LINE_LEN=$((`tput cols` - 1))
 fi
@@ -52,7 +68,7 @@ echo "Root directory: $DIR"
 dir_count=`find $DIR -type d 2> /dev/null | wc -l | sed -e 's/^ *//g;s/ *$//g'`
 
 if $ignore_set; then
-	dir_count=$(($dir_count - `find . -type d 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	dir_count=$(($dir_count - `find . -type d 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 
 echo "Directories: $dir_count"
@@ -60,7 +76,7 @@ echo "Directories: $dir_count"
 file_count=`find $DIR -type f 2> /dev/null| wc -l | sed -e 's/^ *//g;s/ *$//g'`
 
 if $ignore_set; then
-	file_count=$(($file_count - `find . -type f 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	file_count=$(($file_count - `find . -type f 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 
 echo "All files: $file_count"
@@ -71,55 +87,55 @@ echo "File size histogram:"
 # < 100B
 ctg_file_count=`find $DIR -type f -size -100c 2> /dev/null | wc -l`
 if $ignore_set; then
-	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size -100c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size -100c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 fshist="<100 B  :,$ctg_file_count"
 # < 1 KiB
 ctg_file_count=`find $DIR -type f -size +99c -size -1024c 2> /dev/null | wc -l`
 if $ignore_set; then
-	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +99c -size -1024c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +99c -size -1024c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 fshist="$fshist"$(printf '\n<1 KiB  :,')"$ctg_file_count"
 # < 10 KiB
 ctg_file_count=`find $DIR -type f -size +1023c -size -10240c 2> /dev/null | wc -l`
 if $ignore_set; then
-	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +1023c -size -10240c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +1023c -size -10240c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 fshist="$fshist"$(printf '\n<10 KiB :,')"$ctg_file_count"
 # < 100 KiB
 ctg_file_count=`find $DIR -type f -size +10239c -size -102400c 2> /dev/null | wc -l`
 if $ignore_set; then
-	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +10239c -size -102400c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +10239c -size -102400c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 fshist="$fshist"$(printf '\n<100 KiB:,')"$ctg_file_count"
 # < 1 MiB
 ctg_file_count=`find $DIR -type f -size +102399c -size -1048576c 2> /dev/null | wc -l`
 if $ignore_set; then
-	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +102399c -size -1048576c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +102399c -size -1048576c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 fshist="$fshist"$(printf '\n<1 MiB  :,')"$ctg_file_count"
 # < 10 MiB
 ctg_file_count=`find $DIR -type f -size +1048575c -size -10485760c 2> /dev/null | wc -l`
 if $ignore_set; then
-	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +1048575c -size -10485760c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +1048575c -size -10485760c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 fshist="$fshist"$(printf '\n<10 MiB :,')"$ctg_file_count"
 # < 100 MiB
 ctg_file_count=`find $DIR -type f -size +10485759c -size -104857600c 2> /dev/null | wc -l`
 if $ignore_set; then
-	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +10485759c -size -104857600c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +10485759c -size -104857600c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 fshist="$fshist"$(printf '\n<100 MiB:,')"$ctg_file_count"
 # < 1 GiB
 ctg_file_count=`find $DIR -type f -size +104857599c -size -1073741824c 2> /dev/null | wc -l`
 if $ignore_set; then
-	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +104857599c -size -1073741824c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +104857599c -size -1073741824c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 fshist="$fshist"$(printf '\n<1 GiB  :,')"$ctg_file_count"
 # >= 1 GiB
 ctg_file_count=`find $DIR -type f -size +1073741823c 2> /dev/null | wc -l`
 if $ignore_set; then
-	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +1073741823c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "^(\.git|[0-9]+)$" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
+	ctg_file_count=$(($ctg_file_count - `find $DIR -type f -size +1073741823c 2> /dev/null | while read line; do printf "$line" | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | tr -d '\n'; echo ""; done | sed '/^$/d' | wc -l`))
 fi
 fshist="$fshist"$(printf '\n>=1 GiB :,')"$ctg_file_count"
 
@@ -138,8 +154,9 @@ echo "$fshist" | awk -F "," '{printf "  " $1 " "; count = $2; i = 0; while (i++ 
 echo "File type histogram:"
 
 if [ $file_count -gt 0 ]; then
-	fthist=`find $DIR -type f -exec file {} + 2> /dev/null | awk -F ":[ ]+"  '{if (length($NF) > 40) print substr($NF, 1, 40) "..."; else print $NF}' | sort | uniq -c | sort -nr | head -n 10`
-	echo "`find $DIR -type f -exec file {} +`"
+	fthist=$(find $DIR -type f -exec file {} + 2> /dev/null | while read line; do if [ `printf "$line" | sed -e 's/: *[^:]*$//g' | awk -F "/" '{while (i++ < NF) print $i}' | grep -E "$ignore" | wc -l` -eq 0 ]; then echo "$line"; fi ; done | awk -F ":[ ]+"  '{if (length($NF) > 40) print substr($NF, 1, 40) "..."; else print $NF}' | sort | uniq -c | sort -nr | head -n 10)
+	#fthist=`find $DIR -type f -exec file {} + 2> /dev/null | awk -F ":[ ]+"  '{if (length($NF) > 40) print substr($NF, 1, 40) "..."; else print $NF}' | sort | uniq -c | sort -nr | head -n 10`
+	#echo "`find $DIR -type f -exec file {} +`"
 	if $normalize; then
 		usable_len=$(($LINE_LEN - $FTHIST_PREFIX_LEN))
 		max_len=`echo "$fthist" | head -n 1 | awk '{print $1}'`
@@ -151,7 +168,7 @@ if [ $file_count -gt 0 ]; then
 	# Print file type histogram
 	SAVEIFS=$IFS
 	echo "$fthist" | while IFS= read -r line ; do
-		echo "$line" | sed -e 's/^ *//g' | cut -f1 -d' ' --complement | awk '{printf "%-45s: ", $0}'
+		echo "$line" | sed -e 's/^ *[0-9]* *//g' | awk '{printf "  %-43s: ", $0}'
 		echo "$line" | awk '{count = $1; i = 0; while (i++ < count) printf "#"; printf "\n"}'
 	done
 	IFS=$SAVEIFS
